-- =====================================================================
-- PetOS - schema inicial
-- Corresponde ao modelo consolidado nas Sprints 1 e 2:
-- pets, vaccines, routine_records e alerts.
-- =====================================================================

CREATE TABLE pets (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    name        VARCHAR(100) NOT NULL,
    species     VARCHAR(20)  NOT NULL,
    breed       VARCHAR(100),
    birth_date  DATE,
    weight      DOUBLE PRECISION,
    tutor_name  VARCHAR(100) NOT NULL,
    tutor_phone VARCHAR(20),
    active      BOOLEAN      NOT NULL DEFAULT TRUE,
    CONSTRAINT pk_pets PRIMARY KEY (id)
);

CREATE INDEX idx_pets_active ON pets (active);
CREATE INDEX idx_pets_name ON pets (name);

CREATE TABLE vaccines (
    id               BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    pet_id           BIGINT       NOT NULL,
    name             VARCHAR(100) NOT NULL,
    application_date DATE,
    due_date         DATE,
    status           VARCHAR(20)  NOT NULL,
    CONSTRAINT pk_vaccines PRIMARY KEY (id),
    CONSTRAINT fk_vaccines_pet FOREIGN KEY (pet_id) REFERENCES pets (id)
);

CREATE INDEX idx_vaccines_pet ON vaccines (pet_id);
CREATE INDEX idx_vaccines_due_date ON vaccines (due_date);

CREATE TABLE routine_records (
    id          BIGINT      GENERATED BY DEFAULT AS IDENTITY,
    pet_id      BIGINT      NOT NULL,
    type        VARCHAR(20) NOT NULL,
    description VARCHAR(500),
    record_date DATE        NOT NULL,
    CONSTRAINT pk_routine_records PRIMARY KEY (id),
    CONSTRAINT fk_routine_records_pet FOREIGN KEY (pet_id) REFERENCES pets (id)
);

CREATE INDEX idx_routine_records_pet ON routine_records (pet_id);

CREATE TABLE alerts (
    id         BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    pet_id     BIGINT       NOT NULL,
    type       VARCHAR(20)  NOT NULL,
    message    VARCHAR(500) NOT NULL,
    due_date   DATE,
    sent       BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP    NOT NULL,
    CONSTRAINT pk_alerts PRIMARY KEY (id),
    CONSTRAINT fk_alerts_pet FOREIGN KEY (pet_id) REFERENCES pets (id)
);

CREATE INDEX idx_alerts_pet ON alerts (pet_id);
CREATE INDEX idx_alerts_sent ON alerts (sent);

-- =====================================================================
-- PetOS - autenticacao e propriedade do pet
--
-- Introduz usuarios (TUTOR e CLINICA) e vincula cada pet ao seu tutor.
-- owner_id e NULO por design: registros anteriores a autenticacao
-- continuam validos e sao adotados pelo seed na migration seguinte.
-- tutor_name e tutor_phone sao preservados (evolucao nao destrutiva).
-- =====================================================================

CREATE TABLE users (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    name          VARCHAR(100) NOT NULL,
    email         VARCHAR(150) NOT NULL,
    password_hash VARCHAR(100) NOT NULL,
    role          VARCHAR(20)  NOT NULL,
    active        BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMP    NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uk_users_email UNIQUE (email)
);

ALTER TABLE pets ADD COLUMN owner_id BIGINT;

ALTER TABLE pets ADD CONSTRAINT fk_pets_owner
    FOREIGN KEY (owner_id) REFERENCES users (id);

CREATE INDEX idx_pets_owner ON pets (owner_id);

-- =====================================================================
-- PetOS - alerta preventivo vinculado a vacina de origem
--
-- Sem esta coluna nao e possivel distinguir "novo alerta" de
-- "alerta ja existente para a mesma vacina", o que gerava duplicidade.
-- =====================================================================

ALTER TABLE alerts ADD COLUMN vaccine_id BIGINT;

ALTER TABLE alerts ADD CONSTRAINT fk_alerts_vaccine
    FOREIGN KEY (vaccine_id) REFERENCES vaccines (id);

CREATE INDEX idx_alerts_vaccine ON alerts (vaccine_id);

-- =====================================================================
-- PetOS - massa de dados de DESENVOLVIMENTO
--
-- As datas sao relativas a data de execucao para que os estados
-- (vencida / a vencer / em dia) continuem coerentes com a politica
-- de vacinacao ao longo do tempo.
-- Os usuarios de desenvolvimento sao criados pelo DevelopmentDataSeeder,
-- que aplica o hash BCrypt das senhas (nenhum hash e versionado aqui).
-- =====================================================================

INSERT INTO pets (
    name,
    species,
    breed,
    birth_date,
    weight,
    tutor_name,
    tutor_phone,
    active
)
VALUES
    (
        'Thor',
        'DOG',
        'Golden Retriever',
        CAST(CURRENT_DATE - INTERVAL '6' YEAR AS DATE),
        28.5,
        'Carlos Oliveira',
        '(11) 99999-1111',
        TRUE
    ),
    (
        'Luna',
        'CAT',
        'Siamês',
        CAST(CURRENT_DATE - INTERVAL '5' YEAR AS DATE),
        4.2,
        'Carlos Oliveira',
        '(11) 99999-1111',
        TRUE
    ),
    (
        'Bob',
        'DOG',
        'Labrador',
        CAST(CURRENT_DATE - INTERVAL '7' YEAR AS DATE),
        32.0,
        'Pedro Santos',
        '(11) 97777-3333',
        TRUE
    );

-- Vacina vencida: dispara alerta VACCINE_OVERDUE
INSERT INTO vaccines (
    pet_id,
    name,
    application_date,
    due_date,
    status
)
SELECT
    p.id,
    'V10 - Polivalente',
    CAST(CURRENT_DATE - INTERVAL '13' MONTH AS DATE),
    CAST(CURRENT_DATE - INTERVAL '20' DAY AS DATE),
    'OVERDUE'
FROM pets p
WHERE p.name = 'Thor';

-- Vacina dentro da janela preventiva de 30 dias: dispara alerta VACCINE_DUE
INSERT INTO vaccines (
    pet_id,
    name,
    application_date,
    due_date,
    status
)
SELECT
    p.id,
    'Antirrábica',
    CAST(CURRENT_DATE - INTERVAL '11' MONTH AS DATE),
    CAST(CURRENT_DATE + INTERVAL '15' DAY AS DATE),
    'EXPIRING_SOON'
FROM pets p
WHERE p.name = 'Thor';

-- Vacinas em dia: nenhum alerta preventivo
INSERT INTO vaccines (
    pet_id,
    name,
    application_date,
    due_date,
    status
)
SELECT
    p.id,
    'Quádrupla Felina',
    CAST(CURRENT_DATE - INTERVAL '2' MONTH AS DATE),
    CAST(CURRENT_DATE + INTERVAL '10' MONTH AS DATE),
    'APPLIED'
FROM pets p
WHERE p.name = 'Luna';

INSERT INTO vaccines (
    pet_id,
    name,
    application_date,
    due_date,
    status
)
SELECT
    p.id,
    'V10 - Polivalente',
    CAST(CURRENT_DATE - INTERVAL '1' MONTH AS DATE),
    CAST(CURRENT_DATE + INTERVAL '11' MONTH AS DATE),
    'APPLIED'
FROM pets p
WHERE p.name = 'Bob';

INSERT INTO routine_records (
    pet_id,
    type,
    description,
    record_date
)
SELECT
    p.id,
    'WALK',
    'Caminhada de 30 minutos no parque',
    CAST(CURRENT_DATE - INTERVAL '2' DAY AS DATE)
FROM pets p
WHERE p.name = 'Thor';

INSERT INTO routine_records (
    pet_id,
    type,
    description,
    record_date
)
SELECT
    p.id,
    'VET_VISIT',
    'Check-up anual. Peso ideal.',
    CAST(CURRENT_DATE - INTERVAL '30' DAY AS DATE)
FROM pets p
WHERE p.name = 'Thor';

INSERT INTO routine_records (
    pet_id,
    type,
    description,
    record_date
)
SELECT
    p.id,
    'MEDICATION',
    'Vermifugação preventiva',
    CAST(CURRENT_DATE - INTERVAL '5' DAY AS DATE)
FROM pets p
WHERE p.name = 'Luna';

INSERT INTO routine_records (
    pet_id,
    type,
    description,
    record_date
)
SELECT
    p.id,
    'GROOMING',
    'Escovação e limpeza de orelhas',
    CAST(CURRENT_DATE - INTERVAL '1' DAY AS DATE)
FROM pets p
WHERE p.name = 'Bob';

-- Alertas preventivos derivados das vacinas, ja vinculados a vacina de origem,
-- exatamente como o fluxo de vacinacao os geraria em tempo de execucao.
INSERT INTO alerts (
    pet_id,
    vaccine_id,
    type,
    message,
    due_date,
    sent,
    created_at
)
SELECT
    v.pet_id,
    v.id,
    'VACCINE_OVERDUE',
    'Vacina ''' || v.name || ''' do pet ' || p.name ||
    ' está vencida. Regularize o quanto antes.',
    v.due_date,
    FALSE,
    CURRENT_TIMESTAMP
FROM vaccines v
         JOIN pets p ON p.id = v.pet_id
WHERE v.status = 'OVERDUE';

INSERT INTO alerts (
    pet_id,
    vaccine_id,
    type,
    message,
    due_date,
    sent,
    created_at
)
SELECT
    v.pet_id,
    v.id,
    'VACCINE_DUE',
    'Vacina ''' || v.name || ''' do pet ' || p.name ||
    ' está próxima do vencimento. Agende a dose de reforço.',
    v.due_date,
    FALSE,
    CURRENT_TIMESTAMP
FROM vaccines v
         JOIN pets p ON p.id = v.pet_id
WHERE v.status = 'EXPIRING_SOON';