-- =====================================================================
-- PetOS - schema inicial
-- Corresponde ao modelo consolidado nas Sprints 1 e 2:
-- pets, vaccines, routine_records e alerts.
-- =====================================================================

CREATE TABLE pets (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    name        VARCHAR(100) NOT NULL,
    species     VARCHAR(20)  NOT NULL,
    breed       VARCHAR(100),
    birth_date  DATE,
    weight      DOUBLE PRECISION,
    tutor_name  VARCHAR(100) NOT NULL,
    tutor_phone VARCHAR(20),
    active      BOOLEAN      NOT NULL DEFAULT TRUE,
    CONSTRAINT pk_pets PRIMARY KEY (id)
);

CREATE INDEX idx_pets_active ON pets (active);
CREATE INDEX idx_pets_name ON pets (name);

CREATE TABLE vaccines (
    id               BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    pet_id           BIGINT       NOT NULL,
    name             VARCHAR(100) NOT NULL,
    application_date DATE,
    due_date         DATE,
    status           VARCHAR(20)  NOT NULL,
    CONSTRAINT pk_vaccines PRIMARY KEY (id),
    CONSTRAINT fk_vaccines_pet FOREIGN KEY (pet_id) REFERENCES pets (id)
);

CREATE INDEX idx_vaccines_pet ON vaccines (pet_id);
CREATE INDEX idx_vaccines_due_date ON vaccines (due_date);

CREATE TABLE routine_records (
    id          BIGINT      GENERATED BY DEFAULT AS IDENTITY,
    pet_id      BIGINT      NOT NULL,
    type        VARCHAR(20) NOT NULL,
    description VARCHAR(500),
    record_date DATE        NOT NULL,
    CONSTRAINT pk_routine_records PRIMARY KEY (id),
    CONSTRAINT fk_routine_records_pet FOREIGN KEY (pet_id) REFERENCES pets (id)
);

CREATE INDEX idx_routine_records_pet ON routine_records (pet_id);

CREATE TABLE alerts (
    id         BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    pet_id     BIGINT       NOT NULL,
    type       VARCHAR(20)  NOT NULL,
    message    VARCHAR(500) NOT NULL,
    due_date   DATE,
    sent       BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP    NOT NULL,
    CONSTRAINT pk_alerts PRIMARY KEY (id),
    CONSTRAINT fk_alerts_pet FOREIGN KEY (pet_id) REFERENCES pets (id)
);

CREATE INDEX idx_alerts_pet ON alerts (pet_id);
CREATE INDEX idx_alerts_sent ON alerts (sent);

