-- =====================================================================
-- PetOS - autenticacao e propriedade do pet
--
-- Introduz usuarios (TUTOR e CLINICA) e vincula cada pet ao seu tutor.
-- owner_id e NULO por design: registros anteriores a autenticacao
-- continuam validos e sao adotados pelo seed na migration seguinte.
-- tutor_name e tutor_phone sao preservados (evolucao nao destrutiva).
-- =====================================================================

CREATE TABLE users (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    name          VARCHAR(100) NOT NULL,
    email         VARCHAR(150) NOT NULL,
    password_hash VARCHAR(100) NOT NULL,
    role          VARCHAR(20)  NOT NULL,
    active        BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMP    NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uk_users_email UNIQUE (email)
);

ALTER TABLE pets ADD COLUMN owner_id BIGINT;

ALTER TABLE pets ADD CONSTRAINT fk_pets_owner
    FOREIGN KEY (owner_id) REFERENCES users (id);

CREATE INDEX idx_pets_owner ON pets (owner_id);

